### ISSUE TITLE
I have an error the cli is not working

### ISSUE THREAD

**Issue by jojo2600** [chainpoint/chainpoint-cli#3] opened 2018-02-21 21:55 UTC
For example 👍 
If i enter  chp submit abfc4e95bcab8cf9dffdc61a7cb296644a3993505bc3d778d11ff7e7c932bb5e
i get the error Cannot read property 'length' of undefined
Can you check ?

**Comment by grempe** [comment] 2018-02-22 18:06
Thanks for the report. I was unable to reproduce.

```
~ chp submit abfc4e95bcab8cf9dffdc61a7cb296644a3993505bc3d778d11ff7e7c932bb5e
c4b99680-17fa-11e8-a66b-01890c1c3bf5 | abfc4e95bcab8cf9dffdc61a7cb296644a3993505bc3d778d11ff7e7c932bb5e | submitted
c4bf14c0-17fa-11e8-9eeb-014badf22d3f | abfc4e95bcab8cf9dffdc61a7cb296644a3993505bc3d778d11ff7e7c932bb5e | submitted
c4d42360-17fa-11e8-a1d8-01b6fd7f9258 | abfc4e95bcab8cf9dffdc61a7cb296644a3993505bc3d778d11ff7e7c932bb5e | submitted
```

Please let us know if you can still reproduce this, and provide additional details (client version, log output, etc) if so. Until then I will close this issue.

**Closed as completed by grempe** 2018-02-22 18:06 UTC
